apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx
  namespace: foo
  labels:
    name:  nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app:  nginx
    spec:
      containers:
        - image:  pblgllgs/pod:red
          name:  nginx
          ports:
            - containerPort: 80
