apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-management-deploy
  namespace: staging
  labels:
    name: account-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-management
  template:
    metadata:
      labels:
        app: account-management
    spec:
      containers:
        - image: pblgllgs/account-management-service-j17-sb3:0.0.2
          name: account-management
          ports:
            - containerPort: 8082
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
