---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: token-secret
  namespace: staging
spec:
  encryptedData:
    token: AgBnvkPLJtu3wN7mUvBYAHq4JTeAqfaLhtoVyJT7wR1k5XMe4vVVLw6wtiUTFf1c0rYwmuzzHbzk2FtU98ExEYQLlGSSsRW9xtIZRpr2nhzAplx5AS/drZ9ZkmDSsoHcRY/DmUrazAs5mLvyObgt9k2HLigbjNVWS7yiz1YgdUpPwLTPPAq5ZvBUaqig2YqZT1sBuVgK5+SdiZo5z5sgDiePA3Syb5pC9MLV9GfgsUWQiv9VqeHRTUzsRz8AJR6VmelHfMekoDdh9xBIHQXNojn3f4pQ/lQzSRT7UwzOHKwmeedFRGDA/rZBSBA6KehF9JAXB2QGpKLYoQLcsOHeeGE2szGEfW0GSj/abTs8ubOFGct6k/TGNumMLc2GYoggV/E/FjQBzdYUmhj0bRoCPc6BZ/ew8mAKiDv5WHJrJdF8tnJDXDFFaASfAq8dQDEMJQevK9q1RD6syEY21CfAvz5izMy12GE+ZeyP8CLZZYCAJZL44M6NtIViUrRDxosq7onZRZV8NrRQV1IKk25FditCbF3wE47hdM5+TKPWichgn4nw375ip1cXZwlnaPV3/yAbOj8/DkCnc9gckeRZCUa6CUNIyCLImBqKfLiRGjvk2Ys2g5DBEoBsBq1ypZ8rqpIYuGtp40NQO6JX+5opctZ/sVhNV2syzYueIIlR4SqC4IdPXKIGES8Z/zXqT31wgvHhIxd8bnV4wUuFOiTvi/keKjOGilzmY3Q8pm4NPdo20RpmR4X8OpJJ
  template:
    metadata:
      creationTimestamp: null
      name: token-secret
      namespace: staging
