apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-properties
  namespace: staging
data:
  spring-rabbitmq-host: rabbitmq-service
  spring-rabbitmq-port: "30672"
  spring-rabbitmq-password: guest
  spring-rabbitmq-username: guest
  management-endpoints-web-exposure-include: "*"

  api-gateway-environment: docker
  albums-service-environment: k8s
  accounts-management-service-environment: k8s
  users-service-environment: k8s

  config-server-url: optional:configserver:http://config-server:8888