apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap_properties
  namespace: staging
data:
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_PASSWORD: guest
  SPRING_RABBITMQ_USERNAME: guest
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"

  API_GATEWAY_ENVIRONMENT: docker
  DISCOVERY_SERVICE_ENVIRONMENT: docker
  ALBUMS_SERVICE_ENVIRONMENT: docker
  ACCOUNTS_MANAGEMENT_SERVICE_ENVIRONMENT: docker
  USERS_SERVICE_ENVIRONMENT: docker

  CONFIG_SERVER_URL: optional:configserver:http://config-server:8888