apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-properties
  namespace: staging
data:
  spring-rabbitmq-host: rabbitmq
  spring-rabbitmq-port: "5672"
  spring-rabbitmq-password: guest
  spring-rabbitmq-username: guest
  management-endpoints-web-exposure-include: "*"

  api-gateway-environment: docker
  discovery-service-environment: docker
  albums-service-environment: docker
  accounts-management-service-environment: docker
  users-service-environment: docker

  config-server-url: optional:configserver:http://config-server:8888