apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deploy
  namespace: staging
  labels:
    name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - image: rabbitmq:3-management-alpine
          name: rabbitmq
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                configMapKeyRef:
                  name: configmap-properties
                  key: spring-rabbitmq-username
            - name:  RABBITMQ_DEFAULT_PASS
              valueFrom:
                configMapKeyRef:
                  name: configmap-properties
                  key: spring-rabbitmq-password
          ports:
            - containerPort: 5672
            - containerPort: 15672
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-service
spec:
  type: ClusterIP
  ports:
   - name: http
     protocol: TCP
     port: 15672
     targetPort: 15672
     nodePort: 31672
   - name: amqp
     protocol: TCP
     port: 5672
     targetPort: 5672
     nodePort: 30672
  selector:
    app: rabbitmq