apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deploy
  namespace: staging
  labels:
    name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - image: pblgllgs/config-server-j17-sb3:0.0.2
          name: config-server
          env:
            - name: GITHUB_TOKEN
              value: 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
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_PASSWORD
              value: guest
            - name: SPRING_RABBITMQ_USERNAME
              value: guest
            - name:  GITHUB_TOKEN
              value: '*'
          ports:
            - containerPort: 8888
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name:  config-server-service
spec:
  selector:
    app:  config-server
  type:  ClusterIP
  ports:
  - port:  8888
    targetPort: 32888 