apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pc-volume
  namespace: staging
  labels:
    type: local
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pc-volume-claim
  namespace: staging
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: staging
data:
  MYSQL_ROOT_USERNAME: root
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: db_users
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: staging
spec:
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql
          persistentVolumeClaim:
              claimName: mysql-pc-volume-claim
      containers:
        - name: mysql
          image: mysql:8.0.32
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql
          envFrom:
            - configMapRef:
                name: mysql-config
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 750m
              memory: 512Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: staging
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
