apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deploy
  namespace: staging
  labels:
    name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - image: pblgllgs/config-server-j17-sb3:0.0.4
          name: config-server
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: token-secret
                  key: token
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap-properties
                  key: spring-rabbitmq-host
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: configmap-properties
                  key: spring-rabbitmq-password
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: configmap-properties
                  key: spring-rabbitmq-username
            - name:  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              valueFrom:
                configMapKeyRef:
                  name: configmap-properties
                  key: management-endpoints-web-exposure-include
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLE_API
              valueFrom:
                configMapKeyRef:
                  name: configmap-properties
                  key: cloud-kubernetes-secrets-enable-api
            - name: SPRING_CLOUD_KUBERNETES_DISCOVERY_ALL_NAMESPACES
              valueFrom:
                configMapKeyRef:
                  name: configmap-properties
                  key: cloud-kubernetes-discovery-all-namespaces
            - name:  SPRING_CLOUD_KUBERNETES_LOADBALANCER_MODE
              valueFrom:
                configMapKeyRef:
                  name: configmap-properties
                  key: cloud-kubernetes-loadbalancer-mode
          ports:
            - containerPort: 8888
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name:  config-server
  namespace: staging
spec:
  selector:
    app:  config-server
  type:  ClusterIP
  ports:
  - port:  8888
    protocol: TCP
    targetPort: 8888 
