apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-ws-deploy
  namespace: staging
  labels:
    name: account-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-ws
  template:
    metadata:
      labels:
        app: account-ws
    spec:
      containers:
        - image: pblgllgs/account-management-service-j17-sb3:0.0.3
          name: account-ws
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: configmap-properties
                  key: discovery-service-environment
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: configmap-properties
                  key: config-server-url
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name:  account-ws
  namespace: staging
spec:
  selector:
    app:  account-ws
  type:  NodePort
  ports:
  - port:  8082
    targetPort:  32002