apiVersion: apps/v1
kind: Deployment
metadata:
  name: albums-deploy
  namespace: staging
  labels:
    name: albums
spec:
  replicas: 1
  selector:
    matchLabels:
      app: albums
  template:
    metadata:
      labels:
        app: albums
    spec:
      containers:
        - image: pblgllgs/album-service-j17-sb3:0.0.2
          name: albums
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: configmap-properties
                  key: albums-service-environment
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: configmap-properties
                  key: config-server-url
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name:  albums
  namespace: staging
spec:
  selector:
    app:  albums
  type:  NodePort
  ports:
  - port:  8081
    targetPort:  32001