apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-ws-deploy
  namespace: staging
  labels:
    name: accounts-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-ws
  template:
    metadata:
      labels:
        app: accounts-ws
    spec:
      containers:
        - image: pblgllgs/account-management-service-j17-sb3:0.0.4
          name: accounts-ws
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: configmap-properties
                  key: accounts-management-service-environment
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: configmap-properties
                  key: config-server-url
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap-properties
                  key: spring-rabbitmq-host
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: configmap-properties
                  key: spring-rabbitmq-password
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: configmap-properties
                  key: spring-rabbitmq-username
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLE_API
              valueFrom:
                configMapKeyRef:
                  name: configmap-properties
                  key: cloud-kubernetes-secrets-enable-api
            - name: SPRING_CLOUD_KUBERNETES_DISCOVERY_ALL_NAMESPACES
              valueFrom:
                configMapKeyRef:
                  name: configmap-properties
                  key: cloud-kubernetes-discovery-all-namespaces
            - name:  SPRING_CLOUD_KUBERNETES_LOADBALANCER_MODE
              valueFrom:
                configMapKeyRef:
                  name: configmap-properties
                  key: cloud-kubernetes-loadbalancer-mode
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name:  accounts-ws
  namespace: staging
spec:
  selector:
    app:  accounts-ws
  type:  ClusterIP
  ports:
  - port:  8082
    protocol: TCP
    targetPort:  8082