apiVersion: apps/v1
kind: Deployment
metadata:
  name: albums
  namespace: staging
  labels:
    name: albums
spec:
  replicas: 1
  selector:
    matchLabels:
      app: albums
  template:
    metadata:
      labels:
        app: albums
    spec:
      containers:
        - image: pblgllgs/album-service-j17-sb3:0.0.4
          name: albums
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
              value: "true"
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLEAPI
              value: "true"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name:  albums
  namespace: staging
spec:
  type:  ClusterIP
  selector:
    app:  albums
  ports:
  - port:  8080
    protocol: TCP