apiVersion: apps/v1
kind: Deployment
metadata:
  name: albums-ws-deploy
  namespace: staging
  labels:
    name: albums-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: albums-ws
  template:
    metadata:
      labels:
        app: albums-ws
    spec:
      containers:
        - image: pblgllgs/album-service-j17-sb3:0.0.3
          name: albums-ws
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: configmap-properties
                  key: albums-service-environment
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: configmap-properties
                  key: config-server-url
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap-properties
                  key: spring-rabbitmq-host
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: configmap-properties
                  key: spring-rabbitmq-password
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: configmap-properties
                  key: spring-rabbitmq-username
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name:  albums-ws
  namespace: staging
spec:
  selector:
    app:  albums-ws
  type:  NodePort
  ports:
  - port:  8081
    targetPort:  32001