apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: staging
  labels:
    name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - image: pblgllgs/user-service-j17-sb3:0.0.5
          name: users
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
              value: "true"
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLEAPI
              value: "true"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name:  users
  namespace: staging
spec:
  type:  ClusterIP
  selector:
    app:  users
  ports:
  - port:  8080
    protocol: TCP