apiVersion: v1
kind: ConfigMap
metadata:
  name: users
  namespace: default
data:
  application.yml: |-

    clients:
      albums:
        url: http://albums:8080
    spring:
      datasource:
        url: jdbc:mysql://mysql:3306/db_users
        driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
          ddl-auto: update
        properties:
          hibernate:
            show_sql: true
            format_sql: true
            ejb:
              classcache: false
        database: mysql

    gateway:
      api: 192.168.49.2

    token:
      expiration-time: 3600000000
      secret: 7t30WYh7K8A2RQnydbXhNV2150w9ukK30x14awhO3b5253mh1mK4rM2Z9gZksoT3t4NUdC

    login:
      url:
        path: /users/login

    authorization:
      token:
        header:
          name: Authorization
          prefix: Bearer

    management:
      tracing:
        sampling:
          probability: 1.0
      zipkin:
        tracing:
          endpoint: http://zipkin:9411/api/v2/spans
      health.circuitbreakers.enabled: true
      endpoint:
        health:
          enabled: true
          show-details: always
      endpoints:
        web:
          exposure:
            include: '*'
    logging:
      pattern:
        level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]"
      level:
        com:
          pblgllgs:
            users:
              services:
                impl:
                  UserServiceImpl: DEBUG
              clients:
                AlbumClient: DEBUG
              
    albums:
      exception: "Cant connect with albums service"

    resilience4j:
      circuitbreaker:
        circuitBreakerAspectOrder: 1
        instances:
          albums-ws:
            failureRateThreshold: 50
            automatic-transition-from-open-to-half-enabled: true
            waitDurationInOpenState: 10000ms
            slidingWindowType: COUNT_BASED
            slidingWindowSize: 2
            minimumNumberOfCalls: 1
            event-consumer-buffer-size: 10
      retry:
        retryAspectOrder: 2
        instances:
          albums-ws:
            maxAttempts: 3
            waitDuration: 3s
            enableExponentialBackoff: true
            exponentialBackoffMultiplier: 5