apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: default
  labels:
    name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      serviceAccountName: spring-cloud-kubernetes
      initContainers:
        - name: helper
          image: busybox:1.31
          command:
            - "/bin/sh"
            - "-c"
            - |
              until nc -zv mysql 3306
              do
                echo "Esperando a que la DB esté disponible..."
                sleep 2
              done
      containers:
        - image: pblgllgs/user-service-j17-sb3:0.0.6
          name: users
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
              value: "true"
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLEAPI
              value: "true"
            - name: SPRING_MAIN_ALLOWBEANDEFINITIONOVERRIDING
              value: "true"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name:  users
  namespace: default
spec:
  type:  ClusterIP
  selector:
    app:  users
  ports:
  - port:  8080
    protocol: TCP