apiVersion: apps/v1
kind: Deployment
metadata:
  name: albums
  namespace: default
  labels:
    name: albums
spec:
  replicas: 1
  selector:
    matchLabels:
      app: albums
  template:
    metadata:
      labels:
        app: albums
    spec:
      serviceAccountName: spring-cloud-kubernetes
      initContainers:
        - name: helper
          image: busybox:1.31
          command:
            - "/bin/sh"
            - "-c"
            - |
              until nc -zv postgres 5432
              do
                echo "Esperando a que la DB esté disponible..."
                sleep 2
              done
      containers:
        - image: pblgllgs/album-service-j17-sb3:0.0.6
          name: albums
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
              value: "true"
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLEAPI
              value: "true"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name:  albums
  namespace: default
spec:
  type:  NodePort
  selector:
    app:  albums
  ports:
  - nodePort: 32002
    port:  8080
    protocol: TCP
    targetPort: 8080