apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: default
  labels:
    name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
        - image: pblgllgs/api-gateway-j17-sb3:0.0.5
          name: api-gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
              value: "true"
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLEAPI
              value: "true"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name:  api-gateway
  namespace: default
spec:
  type:  NodePort
  selector:
    app:  api-gateway
  ports:
  - port:  8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32001