apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway
  namespace: default
data:
  application.yml: |-

    spring:
      cloud:
        gateway:
          routes:
            - id: users
              uri: lb://users
              predicates:
                - Path=/users/users
                - Method=POST
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/users/(?<segment>.*), /$\{segment}
            - id: users-get-update
              uri: lb://users
              predicates:
                - Path=/users/users/**
                - Method=GET,PUT
                - Header=Authorization, Bearer (.*)
              filters:
                - RemoveRequestHeader=Cookie
                - AuthorizationHeaderFilter=ROLE_ADMIN
                - RewritePath=/users/(?<segment>.*), /$\{segment}
            - id: users-delete
              uri: lb://users
              predicates:
                - Path=/users/users/**
                - Method=DELETE
                - Header=Authorization, Bearer (.*)
              filters:
                - RemoveRequestHeader=Cookie
                - AuthorizationHeaderFilter=ROLE_ADMIN DELETE
                - RewritePath=/users/(?<segment>.*), /$\{segment}
            - id: users-login
              uri: lb://users
              predicates:
                - Path=/users/users/login
                - Method=POST
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/users/(?<segment>.*), /$\{segment}
            - id: users-status-check
              uri: lb://users
              predicates:
                - Path=/users/users/status/check
                - Method=GET
                - Header=Authorization, Bearer (.*)
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/users/(?<segment>.*), /$\{segment}
                - AuthorizationHeaderFilter
            - id: users-actuator
              uri: lb://users
              predicates:
                - Path=/users/actuator/**
                - Method=GET
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/users/(?<segment>.*), /$\{segment}
            - id: users-actuator-circuitbreakers
              uri: lb://users
              predicates:
                - Path=/users/actuator/circuitbreakers
                - Method=GET
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/users/(?<segment>.*), /$\{segment}
            - id: users-actuator-circuitbreakerevents
              uri: lb://users
              predicates:
                - Path=/users/actuator/circuitbreakerevents
                - Method=GET
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/users/(?<segment>.*), /$\{segment}

    token:
      secret: 7t30WYh7K8A2RQnydbXhNV2150w9ukK30x14awhO3b5253mh1mK4rM2Z9gZksoT3t4NUdC
      
    management:
      endpoint:
        gateway:
          enabled: true
      endpoints:
        web:
          exposure:
            include: gateway,health,info,mappings